x <- seq(-1, 1, length=100)
hx <- dnorm(x, mean=0, sd=sqrt(0.01))
labels <- c("mean=0, var = 0.01", "mean=0.1, var = 0.01")
colours <- c("red", "blue")
 plot(x, hx, type="l", lty=2, xlab="x value", ylab ="Density", main = "Comparison of normal distributions", col=colours[1])
 lines(x, dnorm(x, mean=0.1, sd=sqrt(0.01)), col=colours[2])
 legend("topright", title="Distributions", labels, lwd=2, col=colors)
 
 x <- seq(-500, 500, length=10000)
hx <- dnorm(x, mean=0, sd=sqrt(10000))
labels <- c("mean=0, var = 10000", "mean=10, var = 10000")
colours <- c("red", "blue")
 plot(x, hx, type="l", lty=2, xlab="x value", ylab ="Density", main = "Comparison of normal distributions", col=colours[1])
 lines(x, dnorm(x, mean=10, sd=sqrt(10000)), col=colours[2])
 legend("topright", title="Distributions", labels, lwd=2, col=colors)